version: '3'
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
